# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'VSEnterprise-MPN'
    subscriptionId: '0f97cff2-ce2c-4030-b698-36d57e283e52'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'skyline-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/S0meth1ng85/ado-demo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName skyline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
